### ISSUE TITLE
ControllerSettings Window Title not modified

### ISSUE THREAD

**Issue by pduran5** [csutorasa/XOutput#1]
The title is the Controller Setting windows is not modified.

While modifying your code to invert LY and RY axis for Switch Pro Controller support, I fixed this tiny error:
XOutput/UI/View/ControllerSettings.xaml:9
Title="{Binding Model.Title}" Width="800" Height="800" MinWidth="800"

Thanks for this great software!

**Comment by csutorasa** [comment]
Title is fixed in Version 1.5. To invert axes you should input 100% as minimum and 0% as maximum value, it should work as expected.

If you have any further problems or requests, feel free to create a new issue.
Thank you for using the software.
