### ISSUE TITLE
Disabled axis should be centered

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#10]
Currently disabled axis stay left-down
Some gamepads don't have analogs, but they aren't required to play some games

**Comment by alfrix** [comment]
I know you did put a 'Centered' state, which solves it, but it seems to me that it should be handled by the internal logic. 

If input it's disabled and output is LX or LY or RX or RY then return Centered

**Comment by csutorasa** [comment]
So do you want the centered option to be removed, and change the logic in case of two-dimensional axes?

**Comment by alfrix** [comment]
it seems the most logical thing to do, why would someone want the axis to stay left or down, 
the only two axis that should return 0 are LT and RT

**Comment by csutorasa** [comment]
Agreed, will be changed in v1.9

**Comment by csutorasa** [comment]
Fixed in v1.9
