### ISSUE TITLE
Hi, I'm not logging in to the start button

### ISSUE THREAD

**Issue by mohammad-8982** [csutorasa/XOutput#103]
Hi, I'm not logging in to the start button (I installed all the necessary hardware). When logging in, it also says: "Neither ViGEm nor SCPToolkit is installed, please install ViGEm
(I'll repeat that I've got all the prerequisites for Harv even installing vigem)
Please give me guidance. Thank you

**Comment by DuckerMan** [comment]
What's your OS?

**Comment by mohammad-8982** [comment]
OS 7 - 64Bit

**Comment by DuckerMan** [comment]
Can you make screenshot of diagnostic window?

Tools -> Diagnostics

Did you install [that](https://www.microsoft.com/accessories/en-gb/d/xbox-360-controller-for-windows) ?

**Comment by mohammad-8982** [comment]
![Capture](https://user-images.githubusercontent.com/52990254/61633701-e51ce180-aca4-11e9-9833-f26ba09143be.PNG)

**Comment by mohammad-8982** [comment]
Yes, I installed it, but my previous problem has been resolved. Now I start the start button, but when I click the edit button, I'm facing this page.
![Capture](https://user-images.githubusercontent.com/52990254/61633723-f2d26700-aca4-11e9-9d8d-331727c4ed0e.PNG)

**Comment by csutorasa** [comment]
With the 3.19 and later versions you need to add a Game controller with `Add controller` button. Then you can configure it almost the same way as before.

**Comment by mohammad-8982** [comment]
Thank you, my problem was solved. I was ashamed to take your time

**Comment by csutorasa** [comment]
No problem, we all try to help.
