### ISSUE TITLE
Infinite vibration.

### ISSUE THREAD

**Issue by DuckerMan** [csutorasa/XOutput#105]
OS: Windows 7 x64
Vigem is installed.

Games: **The Walking Dead Final Season** and **Assasin's Creed Black Flag**

Sometimes contoller starts to vibrate infinite. If I exit Output it still continues to vibrate. The only solution is unplug contoller and plug it again.

**Comment by csutorasa** [comment]
I will fix this in the next release.

If you face the issue again before the new release, here is a workaround:

- `Stop` emulation
- click input device `Edit`
- click `test` to start vibration, then `stop` the testing

**Comment by DuckerMan** [comment]
If I face that again I'll reopen issue
