### ISSUE TITLE
Allow assigning xinput buttons/directions to mouse

### ISSUE THREAD

**Issue by alb3530** [csutorasa/XOutput#109]
Currently, it's not possible to assign mouse buttons when configuring the controller.

For example, user could want to map left mouse button to D-Pad UP.

But it's currently not possible

**Comment by DuckerMan** [comment]
Don't you think that's could be uncomfortable?

**Comment by csutorasa** [comment]
This is not impossible, but I removed the option a few versions back, as I thought noone uses it.

**Comment by alb3530** [comment]
For people using keyboard + mouse to play, it's a cool addition.

Unless it has some adverse effect (that could be the reason why you removed it).

**Comment by csutorasa** [comment]
It seems that the mouse input was removed as I cannot make it work properly. The current solution only works if the mouse is inside the XOutput window, which is never the case when you are playing.

I know a way to implement it globablly, but most antivirus will think it is some kind of keylogger and delete the application.

**Comment by alb3530** [comment]
> 
> 
> I know a way to implement it globablly, but most antivirus will think it is some kind of keylogger and delete the application.

I've used keyloggers in the past, but at least Windows 10 standard virus protection didn't stop the softwares I've used. (I don't use a third part anti virus)

Also, I think for XOutput power users that want to use this feature, it's not a big deal to add a exception in their anti virus (in case XOutput is flagged as a threat).
