### ISSUE TITLE
Dinput sliders support

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#11]
I really love the program so far, and testing it encountered, a gamepad (Genius G12U) that uses a slider for RY, yes instead of an axis they used a slider, don't know why they did that, but i have disabled it for now. 

[You may also want to show only the axis that are present in the gamepad like this dev did
 https://github.com/Pxtl/XOutput/commit/708dadc0724e9c9bf023c7dc8a9184538816febf](https://github.com/Pxtl/XOutput/commit/708dadc0724e9c9bf023c7dc8a9184538816febf)

**Comment by csutorasa** [comment]
The axis filter shown above is not the best method. I do not check for 0 value, but for correct GUID. Seems to be safer for me, as there may be axes that are at 0 value by default.

Test slider support is added to v1.9. Slider filter is added as well. I do not own a device with sliders, so please confirm if it is working.

**Comment by alfrix** [comment]
Tested 1.9, slider1 is shown at the left and correctly filtered
but **doesn't show up in the list nor is detected when configure** is pressed

![captura](https://user-images.githubusercontent.com/1247237/36230187-566ac32c-11b8-11e8-98e8-14627225e409.PNG)

## If i **manually** add RY=Slider1,100,0 to the config it works fine

![captura](https://user-images.githubusercontent.com/1247237/36230453-353160e8-11b9-11e8-86c8-55a874722803.PNG)

**Comment by csutorasa** [comment]
Can you try the 1.9.1 version? I think the issues should be fixed.

**Comment by alfrix** [comment]
Perfect

**Comment by csutorasa** [comment]
Thanks for your contribution.
