### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#12]
It would be nice to have an icon, maybe an open-source one

Made a couple with inkscape to test
![g4676](https://user-images.githubusercontent.com/1247237/36222597-8bf3d672-11a0-11e8-80cf-ee9e4665ca6c.png)

**Comment by csutorasa** [comment]
Seems to be a good idea. I will check these.

**Comment by alfrix** [comment]
Here the [examples](https://github.com/csutorasa/XOutput/files/1725971/examples.zip) in ico format

**Comment by csutorasa** [comment]
Added to v1.10
