### ISSUE TITLE
Can't configure Steam Controller

### ISSUE THREAD

**Issue by Yoshimit** [csutorasa/XOutput#120]
Hi!
I'd like to map my Steam Controller buttons to XOutput and use it with a UWP game (Minecraft Windows 10 version).

XOutput can't recognize the left analog stick, so I can't use it in game to move the character.
RT and LT buttons are'nt recognized too.

After mapping what is recognized and start, I can see a XBox controller inside Steam, but no left stick.

I'm not sure if I'm doing something wrong or if this will be possible. I just want to let my daughter play Minecraft with Steam Controller.

Any tips? Thank you!

**Comment by csutorasa** [comment]
As the [README.md](https://github.com/csutorasa/XOutput/blob/master/README.md) says, this is a DirectInput to XInput mapper application. There is a chance that the [SharpDX](https://github.com/sharpdx/SharpDX), that I am using can read the input of something that is not DirectInput, but I have not developed that. The SharpDX is no longer maintained, so I do not expect any new features for it.

I am open for new ideas to replace SharpDX, but I have not found any better alternative.

**Comment by Yoshimit** [comment]
Hi!
Thank you for the info. 
I had no idea about DirectInput or XInput.
Seems I'll be unable to use steam controller with Minecraft.
