### ISSUE TITLE
Slider configuration disappeared in 3.23 and 3.24

### ISSUE THREAD

**Issue by Daring-D** [csutorasa/XOutput#124]
Hi,
first of all rumble/vibration is back and working in these versions.

But the analog sliders/triggers can't be configured anymore. In fact they don't even show up in the configuration panel. (In 3.22 this was working fine)
But they do show up in the "controller test" panel. (in your program and windows) And are working there. 

Btw, thanks for this great and very usefull tool!

3.24 "Test panel":
![XOutput 1](https://user-images.githubusercontent.com/57600756/68550100-f9295200-03ff-11ea-8787-ff2bf455d380.jpg)

This is how it looks in 3.24:
![XOutput 2](https://user-images.githubusercontent.com/57600756/68550106-09d9c800-0400-11ea-8069-7586d5a04700.jpg)

This is how it looks in 3.22:
![XOutput 3](https://user-images.githubusercontent.com/57600756/68550211-127ece00-0401-11ea-9dd7-7b28fb9a3f52.jpg)

**Comment by csutorasa** [comment]
Nice catch, fixed in v3.25.
