### ISSUE TITLE
XOutput crash when i plugin gamepad (HidGuardian hidden device) [3.25]

### ISSUE THREAD

**Issue by mlody95pl** [csutorasa/XOutput#125]
XOutput crash when i unplug and plugin my gamepad. Gamepad is hidden in HidGuardian driver, by XOutput affect button.

My settings:
![1](https://user-images.githubusercontent.com/4082647/68582856-08e67c00-047c-11ea-8d0b-4bba0a6c02b9.PNG)
![2](https://user-images.githubusercontent.com/4082647/68582859-097f1280-047c-11ea-8d0d-4e142d04d331.PNG)
![3](https://user-images.githubusercontent.com/4082647/68582860-097f1280-047c-11ea-8c79-b648bc401740.PNG)
![4](https://user-images.githubusercontent.com/4082647/68582861-0a17a900-047c-11ea-99c3-82a89ddc59fe.PNG)
![5](https://user-images.githubusercontent.com/4082647/68582863-0a17a900-047c-11ea-8eb7-5cfe7a815b17.PNG)

When I plug gamepad it's start to stutter all input devices for about 3 sec. It's also crash xoutput and generate ViGEmClient dump file:

Dump file (zipped):
[ViGEmClient.zip](https://github.com/csutorasa/XOutput/files/3831030/ViGEmClient.zip)
Log file:
[XOutput.log](https://github.com/csutorasa/XOutput/files/3831028/XOutput.log)

Sorry for my english

**Comment by KiNGKiMO** [comment]
This issue started at version 3.23.

**Comment by csutorasa** [comment]
This will be fixed in 3.26.
