### ISSUE TITLE
Crash since 3.23 uo tp 3.26

### ISSUE THREAD

**Issue by KiNGKiMO** [csutorasa/XOutput#127]
Hello,

Thank you for the updates..

It's still crashing even after 3.26 release.

It crashes once you click "Edit" button at "Game Contollers".

Also, if you click "Start" and the emulated pad shows, it doesn't work.. you press any button and nothing happen at joy.cpl.

**Comment by csutorasa** [comment]
Can you share the `XOutput.log` file after the crash on v3.26?

**Comment by KiNGKiMO** [comment]
Sure, here you are:
[XOutput.log](https://github.com/csutorasa/XOutput/files/3833022/XOutput.log)

**Comment by csutorasa** [comment]
Did you try to delete `settings.json` file after upgrade?

**Comment by KiNGKiMO** [comment]
Let me try that and get back to you.

**Comment by KiNGKiMO** [comment]
Yes, deleting settings.json worked just fine.

Thank you.

**Comment by csutorasa** [comment]
I am glad that it works, I added a [new section to readme](https://github.com/csutorasa/XOutput/blob/master/README.md#how-to-upgrade).
