### ISSUE TITLE
SCPToolkit Deprecated

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#13]
Since SCPToolkit has been [deptrecated](https://github.com/nefarius/ScpToolkit#archive-statement), a consideration should be made to use the new VIGEm framework, also developed by @nefarius, especifically [ViGEmBus](https://github.com/ViGEm/ViGEmBus)

**Comment by csutorasa** [comment]
I like the idea of it, but I could not find any documentation for the new VIGEm framework. If you can help me with that I might try it.

**Comment by alfrix** [comment]
[I think this serves as the doc for now](https://github.com/nefarius/ViGEm/blob/master/Include/ViGEmClient.h)

[And this is are the samples](https://github.com/nefarius/ViGEm/tree/master/Src/Samples/ViGEmTester)

[For reference here x360ce made the change to ViGEm](https://github.com/x360ce/x360ce/commit/f6188d7aedcf21949d0844b999578e355944af49)

**Comment by csutorasa** [comment]
Added to v2.0
