### ISSUE TITLE
Problems saving configuration (v3.23 - v3.27)

### ISSUE THREAD

**Issue by winqooq** [csutorasa/XOutput#130]
I have two identical gamepads (mac addresses are different), in the system they are defined as:
**Only one** of the two is connected:
Bluetooth Gamepad (c974e020-90ae-11e9-800**5**-444553540000)

**Two are** connected at the same time:
Bluetooth Gamepad (c974e020-90ae-11e9-800**6**-444553540000)
Bluetooth Gamepad (c974e020-90ae-11e9-800**7**-444553540000)

About the problem:
1. I configure two simultaneously connected gamepads (in turn)
2. Save configuration file
3. I disconnect one gamepad (the identifier of the remaining one changes)
4. I configure it
If I click "save configuration" now, the configure "only one is connected" will be saved, bat the configure of "two simultaneously connected" will be deleted
(when configure at the beginning of "one", and then "two", the settings of "one" are deleted)

Just in case, the log and saved configurations with:
[XOutput.log](https://github.com/csutorasa/XOutput/files/3844899/XOutput.log)

[settings - One connected.json.txt](https://github.com/csutorasa/XOutput/files/3844862/settings.-.One.connected.json.txt)
[settings - Two connected.json.txt](https://github.com/csutorasa/XOutput/files/3844863/settings.-.Two.connected.json.txt)

**Comment by csutorasa** [comment]
Settings is really messed up, I will rewrite it in the next version.

**Comment by winqooq** [comment]
Fixed in v3.29
