### ISSUE TITLE
[Question] How to hide real DInput device from games?

### ISSUE THREAD

**Issue by DuckerMan** [csutorasa/XOutput#135]
I've read #28 but I still dont know how to hide real gamepad

**Comment by DuckerMan** [comment]
I installed HidGuardian via this [guide](https://forums.vigem.org/topic/271/hidguardian-v1-driver-installation) and then added my real DInput gamepad as affected.

![image](https://user-images.githubusercontent.com/23637939/70141352-ed9c1480-16a7-11ea-9fb5-1718555f76d5.png)


But the game still uses my real gamepad.

**Comment by csutorasa** [comment]
If you added it as affected device, then you need to unplug and then plug again your device or restart the computer. I think it is mentioned in the installation of HG, but I can add a warning here later.

**Comment by DuckerMan** [comment]
Hah, thanks!
