### ISSUE TITLE
Cant edit anything or Start and Stop

### ISSUE THREAD

**Issue by nerfarnab** [csutorasa/XOutput#139]
I've installed ViGEm drivers but when i run Xoutput it shows just edit the joystick , mouse , and keyboard. And cant edit any buttons, and the start and stop button isn't there. Ive reinstalled everything 3 times now
![image](https://user-images.githubusercontent.com/59321834/71550303-28694200-29f3-11ea-8669-67ef0298d49c.png)
![image](https://user-images.githubusercontent.com/59321834/71550306-3ae37b80-29f3-11ea-809c-5ffe6854ae64.png)

**Comment by csutorasa** [comment]
I guess you have used an older version before. In this version you need to click `Add controller button`, as the input settings and output settings are separated now.
