### ISSUE TITLE
XOutput not recognizing buttons 21 - 32 on vJoy device

### ISSUE THREAD

**Issue by tony8128** [csutorasa/XOutput#14]
I tried to connect my Nintendo Switch JoyCon to my PC using the JoyCon-Driver made by mfosse (https://github.com/mfosse/JoyCon-Driver), and using vJoy to map the pair of JoyCon into one controller. But when I try to map it into an Xbox controller, XOutput doesn't seem to be recognizing buttons 21 to 32, as shown in the following pictures.

![xoutput](https://user-images.githubusercontent.com/3355491/36756477-b2b4c878-1bd4-11e8-88de-92639061c28f.png)
![gamecontroller](https://user-images.githubusercontent.com/3355491/36756483-b77a7bf0-1bd4-11e8-9a69-cf073178df8c.png)

I have tested that all the buttons are recognized by the system's game controller settings, as well as by vJoy. Also all the button mappings for buttons 1 - 20 and the axes are working fine.

I am using vJoy 2.1.8.38-190417 and JoyCon driver v0.9, which should be the latest version for both. I'm also using the latest XOutput v2.0.

**Comment by csutorasa** [comment]
Never seen a device with that many buttons. I will include the fix in the next release.

**Comment by csutorasa** [comment]
Issue is fixed in 1.11 and 2.1 versions. As I do not own a device with more than 20 buttons, could you test if this is resolved?

**Comment by tony8128** [comment]
Thank you so much for your quick response!
However I tested my setup again just now, but buttons over 20 still does not show up in the XOutput GUI. I tried both the 2.1 version and the 1.11 version, and both have the same behavior as the older version.
Really appreciate your help though!

**Comment by csutorasa** [comment]
Sorry for the inconvenience. As I said, I have no way to test this. However I uploaded new 2.1.1 and 1.11.1 versions for testing. Let's see if this will solve the issue.

**Comment by tony8128** [comment]
I have checked both version 2.1.1 and 1.11.1, and they are all working as expected.
One tiny issue: the buttons 21 and over are shown as "Button21", while the buttons before are shown as "B20" for example. However this does not influence the performance of the program by any means.

Thank you again for your quick fixes!

**Comment by tony8128** [comment]
![xoutput_fixed](https://user-images.githubusercontent.com/3355491/36877347-619c76a0-1d7f-11e8-8156-ff9df575c6ec.png)
Might as well put up a screenshot as proof.

**Comment by csutorasa** [comment]
Translations are updated in 1.11.2 and 2.1.2.
