### ISSUE TITLE
How do I compile this project?

### ISSUE THREAD

**Issue by onimac92** [csutorasa/XOutput#142]
I would like to know how to compile this software. I take this opportunity to know what tools the author uses to develop it, for example, what IDE uses.

I would love to learn a little more about its development since it seems to me a very useful tool, especially because I use it every day.

Thank you

**Comment by csutorasa** [comment]
I recommend Visual Studio 2019 (Community edition is free). You can open the `XOutput.sln` it is the solution file, and it will import the projects.
I recommend not using the latest version of source, but the latest released tag version (currently: https://github.com/csutorasa/XOutput/tree/3.26).

**Comment by onimac92** [comment]
Thanks for the reply!
