### ISSUE TITLE
XOutput emulates HID-compliant game controller instead of xBox 360 Game Controller =(

### ISSUE THREAD

**Issue by ArtySh0ck** [csutorasa/XOutput#155]
XOutput emulates HID-compliant game controller instead of xBox 360 Game Controller =(

I did all steps with instructions, already have install ViGEmBus Setup 1.16.116 (as admin), all DirectX and Visual C+ libraries i have too, and no errors, no warnings appear when i start XOutput...

![image](https://user-images.githubusercontent.com/46932541/75353975-e8202600-58b4-11ea-8804-c290bbcb41eb.png)
![image](https://user-images.githubusercontent.com/46932541/75354159-31707580-58b5-11ea-992d-484056dae86d.png)

How can i emulate my old gamepad as xBox 360 Gamepad, please?

**Comment by csutorasa** [comment]
HID means Human interface device, that does not say it cannot be XInput device. Open `File/Game Controllers` and see there if the device is named `Controller (XBOX 360 For Windows)`. If it is not, try to install XBox 360 drivers as well.

**Comment by ArtySh0ck** [comment]
yes, there i have "Controller (xbox360 for windows)". it is good? i thought it has to have a different name.
i have Win10x64 (NTSC) so i cant install legacy driver from download installator. but i can try to install it as windows 7 driver.

**Comment by csutorasa** [comment]
If you have `Controller (xbox360 for windows)` it should be good.
