### ISSUE TITLE
Controller is no longer detected in any computer after unplugging.

### ISSUE THREAD

**Issue by Quick-Brown-Fox-147** [csutorasa/XOutput#156]
I installed XOutput(3.26), configured all buttons and saved the configuration. After that my controller accidentally plugged out and so I plugged it in back . But the controller was not working. So I clicked "File->Game controllers" and selected Xbox controller to see if it would work (At that time two controller was showing despite plugged one. 1.USB, 2.Xbox). It didn't work. I then clicked "Remove" in the XOutout Game controller menu. But then controller was not showing up in my computer. I tried and it is not showing up in any computer. I really need your help.Thanks in advance.
![Damn](https://user-images.githubusercontent.com/59200783/75764988-f369ca80-5d68-11ea-92ba-334ecd691ac8.png)

**Comment by csutorasa** [comment]
Did you install the HidGuardian? It can hide any device, and you might have hidden the original controller.
A warning was in the installation guide of HidGuardian, as it might break any of your devices. So if you do not know what you do, then you can break even your mouse device as well. Please read the usage carefully.

**Comment by Quick-Brown-Fox-147** [comment]
> Did you install the HidGuardian? It can hide any device, and you might have hidden the original controller.
> A warning was in the installation guide of HidGuardian, as it might break any of your devices. So if you do not know what you do, then you can break even your mouse device as well. Please read the usage carefully.

I did not install such thing. This is the first time I have ever heard about "the HidGuardian".

**Comment by Quick-Brown-Fox-147** [comment]
I did not.

**Comment by Quick-Brown-Fox-147** [comment]
Looks like my new controller is done for from using this software. I wish I never had touched this trash.

**Comment by csutorasa** [comment]
I am pretty sure this software cannot ruin your controller. I would recommend connecting to another PC.

**Comment by Quick-Brown-Fox-147** [comment]
I tried connecting it into another pc several times (Windows 7 & 10). It does not show up, no connecting sound, It does not even say controller not recognized, nothing. 

I checked "hidden USB devices" and there's three "**Unknown USB device (Device Descriptor Request Failed)**". I remember trying the controller on three USB port in total. And after I have got this pc, only this USB device is not working. In **Properties>General- Device status** it says ,

"Currently, this hardware device is not connected to the computer. (Code 45)

To fix this problem, reconnect this hardware device to the computer.

A request for the USB device descriptor failed."

In "**properties">"Events**" there's record  as "Device configured" and the last record is "Device not started" (in all three of them). One of them has a "Device deleted" record. 
I connected the controller and tried "**scan for hardware changes**" and also "**update drivers**" for every single USB port. But it says the best driver is already installed.

**Comment by Quick-Brown-Fox-147** [comment]
**This Software can ruin one's game controller. What better example we have here than this issue. I tried everything to fix this but nothing works. My new controller is done for. Once this software messes up your controller, it's over forever.
Don't use this software if you value your controller. Find other alternatives and find trusted ones.**

**Comment by Quick-Brown-Fox-147** [comment]
> I am pretty sure this software cannot ruin your controller. I would recommend connecting to another PC.

**And I have seen this software ruin my new controller before my eyes.**

**Comment by sebsjara** [comment]
> **This Software can ruin one's game controller. What better example we have here than this issue. I tried everything to fix this but nothing works. My new controller is done for. Once this software messes up your controller, it's over forever. Don't use this software if you value your controller. Find other alternatives and find trusted ones.**

a software doesn't have the ability to "remove" the hidden usb descriptor, maybe your controller is a piece of shit and is broken because is garbage.
