### ISSUE TITLE
problem add a affected device to HidGuardian

### ISSUE THREAD

**Issue by amir788** [csutorasa/XOutput#157]
Hi.Problem Xoutput program to set HidGuardian inside program
When selecting an option (add a affected device to HidGuardian)
One Hid Replace AffectedDevices. wrong.Not Work
Must Two Hid Replace AffectedDevices
Picture Problem Down
https://ibb.co/zSHPpZx
https://ibb.co/RcDsTqT

**Comment by findbmx** [comment]
I was also  hoping the "Add affected device to Hidguaurdian" would help the long way inputing HIDs in regedit short.

**Comment by amir788** [comment]
Csutorasa please Answer

**Comment by csutorasa** [comment]
Each device can be added or removed individually, it does not replace anything. The registry contains one device per line and you can add the HID of the devices manually as well, but then restart the application to make sure it will not mess up your current settings.

**Comment by amir788** [comment]
I didn't understand what you mean.
To work HidGuardian should two hid
But One hid Then hit Options(add a affected device to HidGuardian)
You're not fixing it in the new update?

**Comment by amir788** [comment]
Csutorasa please answer

**Comment by amir788** [comment]
Csutorasa?

**Comment by amir788** [comment]
Why didn't you answer?Csutorasa

**Comment by csutorasa** [comment]
I do not understand your problem, do you have a friend who can speak English better?

**Comment by findbmx** [comment]
I'm his friend. The problem is when we use the "add as affected device to HidGuardian" bottom, only one of the Gamepad's HIDs will be copied in the HidGuardian Registry. Now you say one should be enough, but it doesn't work for us. Simply copying one HID line into the registry didnt work for us. And we already know we can manually add gamepad HIDs into the HidGaurdian registry. But since we are introducing the use of XOutput to a lot of people (generally non technical people) - [link](https://4-player.ir/xoutput/) - we hoped the "add as affected device to HidGuardian" bottom could help a lot of people, but we were disappointed.

**Comment by csutorasa** [comment]
Each device needs to be added only once, and the `Add as affected device to HidGuardian` button adds the correct one (at least most of the time). If you have some example hardwareId, where the wrong ID is saved to registry, then please send me them. I can try to have a better logic to find out the registry value.

**Comment by csutorasa** [comment]
I get only 1 hardwareId from the DirectX, and it is like `\\?\hid#vid_046d&pid_c218#9&779538d&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}` and I create `HID\VID_046D&PID_C218` from it.

**Comment by findbmx** [comment]
OK. Sorry I was trying to figure out what exactly the problem is, trying diffrent HIDs. So I should admit that there is only one HID needed for each controller. But what worked for me looks something like this:
`HID\VID_0E8F&PID_3075&REV_0101`
for single gamepads, and for Twin USB Controllers looks like this:
```
HID\VID_0810&PID_0001&REV_0106&Col02
HID\VID_0810&PID_0001&REV_0106&Col01
```
Now I dont know what that "REV_010X" means and where it comes from. but this is what we need to be added to the affected devices.

**Comment by csutorasa** [comment]
Do you think if I add the REV it will be enough? The Col does not seem to be any standard property known by winapi. I can get the VendorID `vid`, the ProductID `pid` and the VersionNumber `rev` more info [here](https://docs.microsoft.com/windows/win32/api/winuser/ns-winuser-rid_device_info_hid).

**Comment by findbmx** [comment]
For me without the col property doesn't work as affected devices. I have tried one HID for both twin controllers like this `HID\VID_0810&PID_0001&REV_0106` also tried the same code twice like this:
```
HID\VID_0810&PID_0001&REV_0106
HID\VID_0810&PID_0001&REV_0106
```
but doesnt help. as soon as I add the Col property for both, it works.
How come you say col property isn't noted?

> Type: USHORT
> The top-level **col**lection Usage for the device.

col stands for collection isn't it?

**Comment by csutorasa** [comment]
`usUsage` is [Usage ID](https://docs.microsoft.com/hu-hu/windows-hardware/drivers/hid/hid-usages#usage-id)

**Comment by findbmx** [comment]
I dont realy understand the concept behind these but look if the information in [this page](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/plug-and-play-support-and-power-management) helps?

**Comment by csutorasa** [comment]
This page is about HID over I2C, most controllers are using USB.

**Comment by findbmx** [comment]
OK I guess I found something this time. [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/hidclass-hardware-ids-for-top-level-collections) it says (under Special purpose hardware ID): 

> - There are no compatible IDs generated by HIDClass
> - Vendor 3rd party INFs must only match against the hardware IDs
> - Hardware IDs that contain HID_DEVICE_SYSTEM_* are “special” devices that the operating system opens for its use. Vendor provided INF must not match on these special hardware IDs.
> - Vendor provided 3rd party HID transport minidrivers must provided the fields listed below to ensure that HIDClass can generate the appropriate hardware IDs.

and one of those mentioned in the fields listed is "Collection number" and it says "only used with multiple-TLC devices". I kinda feel twin controllers must be categorized as multiple-TLC devices.

**Comment by findbmx** [comment]
Seems the new x360ce v.4.10 does it the right way: [link](https://imgur.com/a/1fMSwze)
It's using the Device Instance Path to address Hidgaurdian

**Comment by amir788** [comment]
Please answer @csutorasa 
Thanks

**Comment by csutorasa** [comment]
I can see that, this looks RawInput ID to me. I will play around with this

**Comment by csutorasa** [comment]
Check this test build here.
https://ci.appveyor.com/project/csutorasa/xoutput/builds/33608339/artifacts

**Comment by amir788** [comment]
@csutorasa
https://ibb.co/khPLkJH
Not Work.
One Hid
I think it should be two hid to work
Thanks

**Comment by csutorasa** [comment]
@amir788 can you show what you see in x360ce 4.10?

**Comment by amir788** [comment]
fixed Thanks @csutorasa
The problem was that the prerequisites were not installed
scptoolkit is installed It was red
https://ibb.co/SJMr2X2
The Problem(Bug) Fixed

Use this edition in newer versions of the software
Very Very Thanks

**Comment by findbmx** [comment]
Mine also works only if SCPtoolkit is instaled.

**Comment by csutorasa** [comment]
I will release this soon.

**Comment by csutorasa** [comment]
Released https://github.com/csutorasa/XOutput/releases/tag/3.27

**Comment by amir788** [comment]
@csutorasa
The problem is not solved
Wrong last time .I said the problem is solved
Sorry
------------------------------------------------------------
If you can Edit the program 
When selecting an option (add a affected device to HidGuardian)
Two Hid Replace AffectedDevices
Thanks
