### ISSUE TITLE
Windows 10 gets confused

### ISSUE THREAD

**Issue by FellipePeixoto** [csutorasa/XOutput#158]
Hi! First of all I'm very thankful! Thanks for this awesome software.

specs: Using windows 10 home 64bit. Intel core i3 5th generation, 4GB ram. No video cards.

I having some issues when the program is running, for example with the web browser.
When the firefox is running and the XOutput too, somehow the firefox windows disappear but still running.

Also other problem is when the task bar disappear too ... Some windows for while don't disappear (I'm using unity engine and Visual Studio 2017) and works fine until now.

And the games minimize from times to times.

Did you have some clue about whats going on?

I looked for the log file and I won't find nothing relevant
[XOutput.log](https://github.com/csutorasa/XOutput/files/4340005/XOutput.log)

**Comment by FellipePeixoto** [comment]
I find out that happens each 10 minutes

**Comment by csutorasa** [comment]
I doubt that this software would minimize other applications. I have no timed tasks that run longer than 10 seconds. So 10 minutes seems to be odd anyways. Are you sure XOutput is causing the issue?

**Comment by FellipePeixoto** [comment]
I'm working on tests. I reinstalled windows my computer and created a system restore point. I'll install again. A friend of mine has installed on his computer, I'm waiting for more test from him.

**Comment by FellipePeixoto** [comment]
Well, the error ain't happen anymore... Sorry for the opened issue =/
