### ISSUE TITLE
Exclusivity

### ISSUE THREAD

**Issue by knzchaos** [csutorasa/XOutput#16]
The original Xoutput had the exclusivity checkbox to disable the original dinput controller, but it was only fixed in the source code and never released as an actual release. Is there any way to activate exclusivity in this one? I can't seem to find it. Dead Rising 1 recognizes both real dinput controller and xinput emulated controller.

The reason why I want to emulate it as a x360 controller is because dinput keeps showing numbers instead of actual Xbox buttons, which keeps QTE's very difficult to perform. Thanks in advance.

**Comment by alfrix** [comment]
You are looking for HidGuardian / HidCerberus components from ViGEm. 
HidGuardian is a device driver which can hide controllers from the system. 
HidCerberus is a windows service that allows you to "whitelist" a process

**Comment by csutorasa** [comment]
I have seen some lines of code that might work. I will look into this deeper soon.

**Comment by knzchaos** [comment]
Thanks for the response! Looking forward for it.

**Comment by csutorasa** [comment]
I added exclusive mode to v3.1 for testing. I currently have no way to test this issue, so any feedback is appreciated.

ViGEm HidGuardian and HidCerberus can be a good alternative though if I cannot make exclusive mode work.

**Comment by alfrix** [comment]
@csutorasa unfortunately doesn't work
@knzchaos use [WhiteKnight](https://autohotkey.com/boards/viewtopic.php?t=34890) pick XOutput as the whitelist app, (it uses ViGEm HidGuardian and HidCerberus)

**Comment by csutorasa** [comment]
The [official documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.idirectinputdevice8.idirectinputdevice8.setcooperativelevel(v=vs.85).aspx)  says `nonexclusive access to the device is always permitted, even if another application has obtained exclusive access`. It seems to me, if your game does not acquire the device with exclusive mode, my application cannot do anything to prevent processing the original input.

If you agree, I will remove this (non-working) exclusive functionality in the next release.

**Comment by alfrix** [comment]
I was going to add a how to do exclusive mode, but it's very unstable, very much a [WIP](https://vigem.org/hidguardian-v2-secret-alpha-test-area/) we may have to let some time pass until nefarius figures it out.

**Comment by knzchaos** [comment]
The game is still having the double input problem, I haven't tested the WhiteKnight method but I'll try it soon.
