### ISSUE TITLE
compiling failed with vs2019

### ISSUE THREAD

**Issue by labba** [csutorasa/XOutput#186]
![image](https://user-images.githubusercontent.com/2403858/91860403-4b2fb280-ec74-11ea-81ea-b15b0c92dc04.png)

i was able to resolve NuGet Package version by looking on past issues but after this, i can't compile the code.

**Comment by labba** [comment]
i was able to resolve the first 2 errors that where related to the output metadata by using this solution:
https://stackoverflow.com/questions/1421862/metadata-file-dll-could-not-be-found

but i'm still not able to solve the issue of the not existing tags in the XML..

**Comment by csutorasa** [comment]
Latest master is the alpha 4.x version. It requires .NET core 3.1 with ASP.NET and WPF modules.
