### ISSUE TITLE
Configuration graphics

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#19]
It would be helpful for less experienced users to have visual indications.
I've made some vector graphics [(based on a public domain image)](https://creativecommons.org/publicdomain/zero/1.0/deed.en)
tell me if you are interested, i could give you the svgs or the rasterized pngs if you prefer (i need the output resolution to render them)

![configuration mockups](https://user-images.githubusercontent.com/1247237/37290574-5b5ebd88-25eb-11e8-95ca-903771814104.PNG)

**Comment by csutorasa** [comment]
I am interested for sure. I think WPF is not compatible with SVG by default, but paths can be used in XAML as well. I think I will give a shot to the SVG format first, and if I cannot make it work I will go with PNG.

I think these images are informative, although the ABXY button highlight could be better. If you could tweak them a little that would be perfect.
Thank you for your support.

**Comment by alfrix** [comment]
>I think these images are informative, although the ABXY button highlight could be better. If you could tweak them a little that would be perfect.

### 
Made a slight tweak to ABXY
![red](https://user-images.githubusercontent.com/1247237/37319168-c726ddfa-264c-11e8-93e2-f2d85cd19f7d.PNG)

# Alternative color scheme
![fuchsia](https://user-images.githubusercontent.com/1247237/37319207-e96ecfda-264c-11e8-9ef7-e13b2cd5f6dc.PNG)

# Alternative idea, flashing 2 images:
![lx](https://user-images.githubusercontent.com/1247237/37319221-fa4d3954-264c-11e8-96a6-bb09c8222cbf.gif)
![a](https://user-images.githubusercontent.com/1247237/37319222-fa7c3c68-264c-11e8-9e2f-e971854609df.gif)
![b](https://user-images.githubusercontent.com/1247237/37319219-fa292596-264c-11e8-9166-df376214cff6.gif)

Here is the packaged vector graphics: [X360.zip](https://github.com/csutorasa/XOutput/files/1805221/X360.zip)

If you want to make changes or use PNGs, let me know.

**Comment by alfrix** [comment]
Perhaps (SharpVectors)[https://archive.codeplex.com/?p=sharpvectors] could help on the XAML conversion

**Comment by csutorasa** [comment]
SharpVectors could not load the base svg file, so I had to find another tool. Inkscape does the job.

I think performance problems may occur if I use all of your files without changes. I will use the differences from the base file, and make everything dynamic in the application. Two state alternating images seems to be better for me, so I will use those.

I will include it in the next release for sure.

**Comment by alfrix** [comment]
> Inkscape does the job.

i didn't knew that it could export XAML directly, great!

> I will use the differences from the base file

An excelent idea since on the buttons only the fill color it's changed, and the alternating arrow only changes positions:

```
<PathGeometry Figures="m 98.319413 495.21673 -28.327907 20.72656 -28.091425 21.25781 28.091425 21.25586 28.327907 20.72852 0.122557 -21.64063 h 37.55247 V 516.8554 H 98.44197 Z" FillRule="NonZero"/>
```
```
<PathGeometry Figures="m 249.31353 495.21673 28.3279 20.72656 28.09143 21.25781 -28.09143 21.25586 -28.3279 20.72852 -0.12256 -21.64063 H 211.6385 V 516.8554 h 37.55247 z" FillRule="NonZero"/>
```

**Comment by csutorasa** [comment]
I added this feature to v3.2.
