### ISSUE TITLE
Microsoft 360 Wireless Wheel

### ISSUE THREAD

**Issue by Frakatchoo** [csutorasa/XOutput#2]
Hi ! I would like to play Forza (7 or Horizon 3) with a Microsoft 360 Wireless Wheel.
I can configure my steering wheel in Xoutput, but when I click on "Start" nothing happens.
I do not know if it's using Xinput or DirectInput, that may be the problem, but I did not find any solution.
Thanks!

**Comment by alfrix** [comment]
@Frakatchoo install the scptoolkit, then use the scp-cleanwipe utility that comes with it to remove any traces of the driver, then install this driver [ScpDriver.zip](https://github.com/csutorasa/XOutput/files/1725851/ScpDriver.zip) which is an older extracted from [here](https://github.com/Stents-/XOutput/releases) one that works for me, you can uninstall the scptoolkit afterwards only the driver is needed

**Comment by alfrix** [comment]
you can check if it's working by going to > File/Game Controlers. 
A new Controller (XBOX 360 for Windows) should appear when you click Start

Note: if you are using windows 7 [the 360 controller driver is required](https://www.microsoft.com/accessories/en-us/products/gaming/xbox-360-controller-for-windows/52a-00004#techspecs-connect)

**Comment by csutorasa** [comment]
@Frakatchoo is inactive, so I will close the issue. Reopen it, if you think it is still a valid issue.
