### ISSUE TITLE
Start controller when open application

### ISSUE THREAD

**Issue by camarade35** [csutorasa/XOutput#24]
First time, thx, really

Possible activate controller when open application ?
Not need press start (actually if you close application, all stop, so...)
Like this, we launch a game and can launch XOutPut at the same time and close it when leaving the game

**Comment by csutorasa** [comment]
Hi @camarade35, you are welcome.
Currently if my application is closed, I can handle that and stop all virtual devices. This was a simple task.

However you suggest that I should watch all currently running applications on your computer and check if a new is started. Even if I know a new program (or game) is started I cannot decide if it is a game or just a regular application. The same applies to closing the program (or game).
If you have any idea how to detect recently started or closed programs and decide whether they are games or not, I will try to implement the code, but I cannot think of any solution for this right now. I am curious how you think this could be solved.

**Comment by camarade35** [comment]
I use a lot of autohotkey for the launch of my games (to launch xpadder or joytokey) etc.
the idea would be that XOutput can be started with the validation of the controllers, without having to click on start.
Then in ahk, just throw like this
Run, XOutput / XOutput.exe
Sleep, 100
Run, folder / game.exe (for exe)
Run, steam: // rungameid / 678950 (for steam game)
I'm using XOutput for DBFz because x360ce is rejected by the game launch control now
And sorry, google translator

**Comment by csutorasa** [comment]
If I understand everything, you want to start XOutput then automatically start the emulation of the XInput device. That is possible. Will be added in a future release.

**Comment by csutorasa** [comment]
A new argument will be added in v3.3. A new command line argument is added to auto start devices `--start=`.

If you have a controller named `Logitech RumblePad 2` then you can auto start it with `XOutput.exe --start="Logitech RumblePad 2"`.

**Comment by camarade35** [comment]
Really good
![capture](https://user-images.githubusercontent.com/8459389/37994278-5c9a5946-3211-11e8-8f56-63e9ad4a9a53.PNG)
can we start several controllers or only one name is enough?

**Comment by csutorasa** [comment]
It will start all controllers whose name contains the command line argument. In your case it will start 4 devices. Is it ok for you?

**Comment by camarade35** [comment]
Perfect for me, I wait the new release, Thx for players really ;)

**Comment by camarade35** [comment]
Just to say a new thanks, I can work with this ahk

**#SingleInstance Force
SetWorkingDir, A_ScriptDir

Run, ../../Utilities/XOutput/XOutput.exe --start="THT Arcade console 2P USB Player",, Minimize
Run, steam://rungameid/678950

ExitApp
return**
