### ISSUE TITLE
Can't map Dpad

### ISSUE THREAD

**Issue by ShobuPrime** [csutorasa/XOutput#3]
To whom it may concern,

I noticed if the source controller is being read as not having a dpad, I'm not able to map the Xoutput dpad at all, whereas a different fork of XOutput allows me to do so with no issues.

For reference, I have a 3DS receiving input through vJoy, which is being fed to Xoutput

Thanks

**Comment by csutorasa** [comment]
Seems to be a reasonable request for me. I will include it in the next version.

**Comment by csutorasa** [comment]
Added to 1.7.
