### ISSUE TITLE
Missing Trigger Detection

### ISSUE THREAD

**Issue by ruhtraeel** [csutorasa/XOutput#32]
Hi,
It seems as though this application is missing some trigger functionality of a DirectInput controller.

Using this website: http://html5gamepad.com/

I can see that the triggers of my DirectInput controller are recognized as Axis 4 and Axis 5.
However, it seems as though these axes are not handled in the program, as I do not see any feedback when I press the triggers (In the program on the left side, A7 and A8 seem to be unused, as nothing on my controller shows any response. Perhaps there can be functionality to replace those axes with any directinput axes of the user's choosing).

I have only briefly looked at the code, so I am not sure whether the problem lies in a missing mapping to an enum in DirectInputTypes, or if the axes are only missing in the UI.

I will clone the repo and investigate when I have the time, and will send a pull request if I figure out the issue.

Thanks

**Comment by csutorasa** [comment]
Hi, I am not sure what could go wrong. #11 shows it is working for some controllers. Thank you for your investigation.

**Comment by csutorasa** [comment]
Any updates on this issue?

**Comment by csutorasa** [comment]
Closed due to inactivity. Reopen if needed.
