### ISSUE TITLE
Vibration not working

### ISSUE THREAD

**Issue by soondol007** [csutorasa/XOutput#35]
Hi csutorara

I tried Dualshock4 with strikepack
Strikepack is Dualshock4 accessory (http://collectiveminds.ca/strikepack/)
Button mapping is perfect but there's no vibration even vigem driver installed
So I tried dualshock4 alone again but still no vibration

**Comment by csutorasa** [comment]
Hi, I have checked the [Microsoft documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ee417536(v=vs.85).aspx). I found that my Logitech device does not need all parameters to be sent according to specification. I changed the code to work as the specification says.

**Comment by csutorasa** [comment]
Make sure all drivers are installed properly. If it is still not working reopen this issue.
