### ISSUE TITLE
Logitech Formula Force RX Wheel | Forza Horizon 3 | Dead Zone Issuses

### ISSUE THREAD

**Issue by serJOOga** [csutorasa/XOutput#37]
Hi, first of all i wanted to tanks all People who developed this program! Its very cool!
I tried the last 2 months to Play Forza with my old Logitech Formula Force RX.

- First i tried with x360ce, it recognizes the Logitech Wheel, but not in Game.
- Than i tried XOutput.v0.11, it works well, but had the "Camera Stuck" Bug, because i could not set the Axis 2 to "Disabled" (there was no option for that)

- And now i try your XOutput 3.7.1. It works fine! BUT i got two Problems: 
1. When i in game and choose the "inside car" view, i rotate the wheel and the wheel in game start rotate to late. They are (+15°) - (-15°) degree that the game not recognize. But in the XOutput menu, i can see the red dot clearly move in the sector between (+15°) - (-15°). When i set the "dead zone" in XOutput it gets worse.
PS: I recognize that this effect does not occur in XOutput.v0.11   

2. There is a delay of about 0.5 seconds, like: I turn the wheel, 0,5 seconds, than the car wheels turn.

I dont know what it is. 
PS: I am from germany (But can also speak russian and can help with german translation) and yes i know my english my English is not the best :)

**Comment by ardor97** [comment]
@serJOOga If you want to help with German translation please visit wiki: [](https://github.com/csutorasa/XOutput/wiki/Translation) where you can find all information how to add the translation.

**Comment by csutorasa** [comment]
1. The dead zone issue may come from your game. Have you checked if the game adds the dead zone? You can make sure if you check it in Windows game controller tool. Setting dead zone in XOutput should make your problem worse.
2. The delay is strange for me. XOutput tries to read input as fast as the computer allows it. With an idle CPU it usually can read input in a few milliseconds (5-15 ms). If you are playing a high end game like Forza Horizon 3, your CPU may be busy most of the time. You can try to increase the priority of XOutput in Windows Task Manager. That means if you may have some lags already in game but the input should be read more often and the delay may decrease. I will look into performance anyways.

German and Russian translation would be appreciated. Just follow the instructions linked above.

**Comment by serJOOga** [comment]
I did the German translation yesterday. I dont know if i did it right:
https://raw.githubusercontent.com/serJOOga/XOutput/serJOOga-patch-1/XOutput/Resources/languages.txt

**1.** Yes, the game has settings to set the deadzone. But i set all to zero. I set the XOutput deadzone to zero too.

**2.** Tried to set priority to "high" but nothing changed. But i can live with this issue. 

The biggest Problem is the dead steering angle in the middle. I have to turn the wheel a lot, until there is a reaction in the game :/ Im just wonder why it works with the old XOutput.v0.11.

![001](https://user-images.githubusercontent.com/38536525/39207656-d1e714c8-4800-11e8-97ba-b9ed6f077ff9.png)

**Comment by serJOOga** [comment]
Ok, i created a pull request with the German translation.
It may be the game which has problems with it. I will try another race game.

Anyway thanks a lot. Maybe I just have to get a new steering wheel 😀

**Comment by csutorasa** [comment]
I modified German translation a bit to match other languages in display. But it was good, thanks for support.

I assumed so far that the Dead zone of the devices are set to default 0 by default. This may not be true, so now the dead zone is set manually at start to 0 with v3.8.1. My device is working perfectly with and without this setting. As I cannot reproduce the dead zone issue, I think it may be your device.
