### ISSUE TITLE
Force Feedback Not Working

### ISSUE THREAD

**Issue by daveb778** [csutorasa/XOutput#41]
I managed to get my controller working but i dont have force feedback. I've installed the VIGEM driver but it still doesnt work.
![image](https://user-images.githubusercontent.com/18433196/39332152-9c354e92-4974-11e8-9ebf-45c168183455.png)
![image](https://user-images.githubusercontent.com/18433196/39332157-a0adacbc-4974-11e8-9f07-f8cd1cb0e433.png)

**Comment by csutorasa** [comment]
Sorry this is my fault, this error message is displayed if any error occurs. I think XOutput cannot find any force feedback actuator. That my happen if drivers are not installed properly for your device. Are you sure that your device drive is up-to-date?

**Comment by daveb778** [comment]
I have a afterglow controller that comes with a wireless dongle it works in windows as a dinput device tho there is no force feedback in software. The controller itself does have motors for it, so im not too sure what the issue is.

**Comment by daveb778** [comment]
Windows auto installs drivers for this controller and as far as i can tell there isnt any downloadable ones.

**Comment by csutorasa** [comment]
Have you ever used force feedback before? I mean without XOutput, any game or test application.

**Comment by daveb778** [comment]
Nah i haven't been able to get it to work on anything else.

**Comment by csutorasa** [comment]
I have added a diagnostics screen to v3.9. You can see Force feedback motors count. If it is 0, then the motors cannot be recognized. It may be a driver or device issue, but I cannot help with that. If the motor count is higher than 0, I will look into this issue again.

**Comment by daveb778** [comment]
It does say 0 damn, that sucks cause there is not other driver i can find for this controller. Thanks for the help anyways.
![image](https://user-images.githubusercontent.com/18433196/39599475-f3d07b02-4ee9-11e8-9a88-a6537fafeb9d.png)

**Comment by csutorasa** [comment]
I am sorry, but there is nothing I can do.

**Comment by greywind7** [comment]
Just wondering. My gamepad has one motor only so whether it automatically takes it as the main motor or not. In x360ce I have to swap motor myself
