### ISSUE TITLE
Program breaks when mapping inputs to keyboard.

### ISSUE THREAD

**Issue by carks32** [csutorasa/XOutput#44]
In XOutput 3.9, for some reason, it breaks. It didn't happen before on 3.8.1. Here's the output on XOutput.txt

> 2018-05-03 17:46:57.844 -04:00 INFO  LanguageManager.set_Language: Language is set to English
2018-05-03 17:46:57.844 -04:00 INFO  MainWindowViewModel.Initialize: Loading settings was successful.
2018-05-03 17:46:58.282 -04:00 INFO  GameController.createXOutput: ViGEm devices are used.
2018-05-03 17:46:58.282 -04:00 INFO  MainWindowViewModel.RefreshGameControllers: Mayflash Arcade Stick(9fcdd800-449a-11e8-8004-444553540000) is connected.
2018-05-03 17:46:58.282 -04:00 INFO  GameController.createXOutput: ViGEm devices are used.
2018-05-03 17:46:58.282 -04:00 INFO  MainWindow.WindowLoaded: The application has started.
2018-05-03 17:47:00.092 -04:00 INFO  MainWindowViewModel.VersionCompare: Version is up-to-date
2018-05-03 17:47:00.342 -04:00 INFO  MainWindowViewModel.SaveSettings: Saving settings was successful.
2018-05-03 17:47:03.222 -04:00 ERROR MainWindowViewModel.UnhandledException: System.Windows.Markup.XamlParseException: Se produjo una excepción al establecer la propiedad 'System.Windows.Controls.ContentControl.Content'. ---> System.ArgumentException:  cannot be translated
   en XOutput.UI.Converters.DynamicLanguageConverter.Convert(Object[] values, Type targetType, Object parameter, CultureInfo culture)
   en System.Windows.Data.MultiBindingExpression.TransferValue()
   en System.Windows.Data.MultiBindingExpression.Transfer()
   en System.Windows.Data.MultiBindingExpression.UpdateTarget(Boolean includeInnerBindings)
   en System.Windows.Data.MultiBindingExpression.AttachToContext(Boolean lastChance)
   en System.Windows.Data.MultiBindingExpression.AttachOverride(DependencyObject d, DependencyProperty dp)
   en System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)
   en System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   en System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   en MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   en MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   en System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   en System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   en System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   en XOutput.UI.Windows.AutoConfigureWindow.InitializeComponent()
   en XOutput.UI.Windows.AutoConfigureWindow..ctor(AutoConfigureViewModel viewModel, Boolean timed)
   en XOutput.UI.Component.MappingViewModel.Configure()
   en XOutput.UI.Component.MappingView.ConfigureClick(Object sender, RoutedEventArgs e)
   en System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   en System.Windows.Controls.Primitives.ButtonBase.OnClick()
   en System.Windows.Controls.Button.OnClick()
   en System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   en System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   en System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   en System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   en System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   en System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   en System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   en System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   en System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   en System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   en System.Windows.Input.InputManager.ProcessStagingArea()
   en System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   en System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   en System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   en System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by csutorasa** [comment]
Try the hotfix in v3.9.1.
