### ISSUE TITLE
Vibration not working in games that supports xinput

### ISSUE THREAD

**Issue by mactyre** [csutorasa/XOutput#47]
Hello I've experienced a problem where force feedback or vibration works in games that only support directinput like ( need for speed underground 1 ) but in the same when I try to play a game that supports xinput like Dirt3 my controller doesn't vibrate at all

Update: Just tried another game (JustCause2) which also supports xinput and the vibration actually worked but was acting weird it just alters the speed from super low to really high randomly, sometimes it would be really high even though I'm just standing and not doing anything

Update2: tried another directinput game Need for speed Most wanted (2005) and this time vibration didn't work.
I don't really know what's wrong maybe it's something on my end? I'm sorry if this seems pointless to you

**Comment by mactyre** [comment]
so after few more tests it turns out that my controller wasn't vibrating in Dirt3 because the game supports both dinput and xinput so I've downloaded dinput8-x360ce21 which acutally stops the game from reading dinput and only reading xinput and vibration started working normally

So I guess I'm better playing dinput games like (nfsMW) and (nfsUG) with my controller without any software and playing games that support xinput using xoutput is that correct?

**Comment by csutorasa** [comment]
Hello, you are right. If the game supports dinput, you do no need anything, just play the game. If it is xinput and does not recognize your controller, then use XOutput to play.

**Comment by mactyre** [comment]
Thanks for your reply, what about the dll that I mentioned though should I keep on using it ?
would it be of any help to you in making that "exclusivity" feature everyone is talking about?
Of course I don't mean any disrespect or telling you what to do, I'm merely asking questions.

**Comment by csutorasa** [comment]
There are a few ways to block the Dinput from the games. If they work properly then you can use it. If you face any issues, it is better to play without XOutput and the blocker.
Exclusivity is difficult to achieve, as I do not want to modify game files. Some games may ban you for that.
