### ISSUE TITLE
Block keyboard's input

### ISSUE THREAD

**Issue by carks32** [csutorasa/XOutput#48]
Can you make it so if you have the keyboard enabled as a controller, make these inputs not work as keyboard-detected? I don't know if I'm explaining well, but see, some games like Melty Blood, detect certain motions weirdly in my keyboard, but as a controller it inputs them well.

**Comment by csutorasa** [comment]
Would you like me to hide keyboard input from the game?

**Comment by carks32** [comment]
Yeah basically. This way, you can't make double input because some games would put both the controller and the keyboard as players.

**Comment by csutorasa** [comment]
I do not think my application will ever be able to do that. Basically your request even more difficult to implement than my other exclusivity issue #28. Sorry you need to look for a workaround for that, maybe [HidGuardian](https://github.com/ViGEm/HidGuardian) help you.
