### ISSUE TITLE
Nintendo switch pro controller is abit glitchy

### ISSUE THREAD

**Issue by mariodk** [csutorasa/XOutput#49]
when connecting over bluetooth this works fine
but when connecting over the wire(1st party cable even) if Steam is running
its like most of the buttons is rapid pressing and some is rapid pressing
and some others is held down forever
even without im touching the controller
but when connecting without steam is running Xoutput see the pro controller but dont register the inputs at all

will be neat if this can be fixed somehow
since i just got a Nswitch pro controller
want it to use both on PC(as Xinput) and over wire & nintendo switch over wireless
so i dont have to reconnect the controller each time im changing from PC to switch & visa versa
and i know Steam add a form of support to Nswitch pro controller and its not really usefull outside steam like emulators + Steam dont convert it into Xinput sadly 
and the nice thing about convert every controller to Xinput+this program is
no matter what controller i plugin i dont have to Reconfig the emulator´s/game´s settings
since i use my mayflash usb gamecube adapter(PC mode) for some emulators/games
and Nswitch pro controller for also emulators/some other games and both at same time if multiplayer

**Comment by csutorasa** [comment]
XOutput can only use the input, that Windows DirectX gives. You can check in File/Game controllers menu what the actual input is. If it is just rapid button presses there too, I am afraid I cannot help with this.

If Steam uses an emulation that works only in Steam games, then I cannot use that input. I do not want to add any Steam specific changes, as you may get ban from Steam games for that.
