### ISSUE TITLE
Axis directions

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#5]
The gamepad config screen showing inputs and outputs i'ts very nice, but needs something like the control panel moving cross to tell directions
maybe something like this:
![1](https://user-images.githubusercontent.com/1247237/35629262-e5eff8c4-067c-11e8-848c-2dfc2eeedafe.JPG)

**Comment by csutorasa** [comment]
I like the idea of two-dimensional axes. A solution like this will be added in the next release.

**Comment by csutorasa** [comment]
Added to 1.7.
