### ISSUE TITLE
Joystick order problem

### ISSUE THREAD

**Issue by mkultimate** [csutorasa/XOutput#50]
hello, the XOutput presents a problem when it closes and turns open changes the order of the joystick example at the moment is the joystick # 1 but when it becomes open and loads the controllers switches joystick # 2 are left for games as the second player I use a convert from ps2 to usb pad I mention this problem because sometimes I use the joytokey and it always changes the order

**Comment by csutorasa** [comment]
Hi, nice catch. The next release will start controllers in order of their displayed name. So if you use the same controllers, they will start in order.

**Comment by mkultimate** [comment]
thank you very much for your great help
