### ISSUE TITLE
Rumble not working.

### ISSUE THREAD

**Issue by damianshrinivas** [csutorasa/XOutput#52]
Ok, so my gamepad is a custom Dinput GameCube USB controller (USB Network Joystick in device manager)
Everything works except for vibration function, in XOutput the test option is vibrating normally but in games - not. Windows 10 x64 newest update. Maybe because the original dinput gamepad driver is 32 bit?

**Comment by csutorasa** [comment]
I think you should try the 64 bit driver. If that does not work, install the official [XBox 360 controller drivers](https://www.microsoft.com/accessories/en-gb/d/xbox-360-controller-for-windows).

**Comment by csutorasa** [comment]
Closed due to lack of response, reopen if needed.
