### ISSUE TITLE
Keyboard input support for missing controllers buttons

### ISSUE THREAD

**Issue by MairusuPawa** [csutorasa/XOutput#53]
Hello!

I am using a few legacy controllers with Xoutput, such as a Sega Saturn one with a Mayflash USB adapter. Such controllers have less buttons than a Xinput one - for instance there are not Back or Guide buttons on the Saturn one for reasons obvious.

Unfortunately some modern games still expect all Xinput buttons to be used in some way, and sometimes there are no easy workaround. In most case, the buttons still are rarely used, meaning it's okay if there are not easily accessible on a controller but on a side keyboard. So I'd like to map a few buttons to a regular keyboard in addition to the gamepads, to make up for the lack of them on a controller.

Would that be possible to implement? Thanks!

**Comment by csutorasa** [comment]
The possibility of creating one controller from different ones will come in 4.x releases. I do not have any working 4.x build yet, work in progress.

**Comment by csutorasa** [comment]
Fixed in v3.19, but keyboard can be treated differently in some games.
