### ISSUE TITLE
Lag, trigger issue

### ISSUE THREAD

**Issue by jnowak1054** [csutorasa/XOutput#56]
Utilizing a thrustmaster Ferrari legend edition wheel, the throttle pedal (A6) does not show up under direct input, but an unresponsive or non input A3 does show up; Similar to issue Missing Trigger Detection #32 
![somewhat functional settings](https://user-images.githubusercontent.com/13458023/43627190-e60b4934-96ba-11e8-8890-0a0bc3894105.png)
I used the suggestion from Dinput sliders support #11, I edited the settings text (R2=Axis6,100,0,0) to include mapping A6 to RT which can be seen in above Screenshot. A6 (Throttle pedal) does indeed map to RT, but only updates when a natively XOutput listed direct input is changed. The delay until another input is made is clearly seen under the XInput, or noticed while gaming. No delay until input is detectable in HTML5 Gamepad Tester, XOutput .11, Thrustmaster setup, or games compatible with this wheel. Certainly makes for an exciting driving experience when the throttle is stuck full open until you turn the steering wheel, lol. This may be what Dead Zone Issuses #37 was experiencing as .5 second delay? Oddly, using HTML5 Gamepad tester http://html5gamepad.com/, Axis 5 (throttle A6) maps to B7.
![html5 gamepad tester](https://user-images.githubusercontent.com/13458023/43628740-d4b05db8-96c0-11e8-8de8-35ef704119da.png)

Note: XOutput.11 seemed to recognize all inputs properly, but non mapped analog outputs created other more severe problems.

**Comment by csutorasa** [comment]
- Trigger/axis detection may not work properly, I will look into that, but it is hard to find out as all my test devices are working properly.
- Delay is unnoticeable for me in HTML gamepad tester. If you CPU is utilized for 80-100%, then the  XOutput, running in the background, may have lower chances to run, therefore delay starts to rise. If you have high CPU usage during games, I would recommend increasing the priority of XOutput in task manager, but that may cause lag in games. Thus the XOutput is triggered around 64 fps, but this issue has no real solution ([see more](https://social.msdn.microsoft.com/Forums/vstudio/en-US/facc2b57-9a27-4049-bb32-ef093fbf4c29/threadsleep1-sleeps-for-156-ms?forum=clr)).
- B6 and B7 are called buttons, but as you can see they have other values than 0 and 1. In most games with XBox controller, B6 is used for brake and B7 is for throttle. I should not be an issue.

**Comment by KingFoxxy** [comment]
I have a Thrustmaster Ferrari Experience GT and I'm experiencing the same problem. Right trigger doesn't work and if I add it manually to the settings it only works while turning the wheel (it's stuck unless the wheel is moving).

**Comment by csutorasa** [comment]
If you need to add the setting manually the refresh will not work. The main issue is that the axis (A6) is not recognized.
I do not own the device, so I added extended logging in v3.12. You should send me the a log file. Just start the application and exit is after a few seconds.

**Comment by KingFoxxy** [comment]
Ok, here it is, I hope it's the right one. Thanks for the effort towards fixing this issue :)
[XOutput.log](https://github.com/csutorasa/XOutput/files/2357521/XOutput.log)

**Comment by csutorasa** [comment]
This is the right file, but you have not updated to the latest version yet. Please download the [latest release](https://github.com/csutorasa/XOutput/releases/latest).

**Comment by lelopes05** [comment]
I have the very same problem with Thrustmaster Rumble Force (it is almost identhical to the ferrari one)
I spend some money on this thing but can't get it working with any game. Tryed other emulators like x360ce, it recognizes all axis but simply wont work with any game i have. Xoutput on the other hand, works great, except for the accelerator. lol
[XOutput.log](https://github.com/csutorasa/XOutput/files/3337514/XOutput.log)

**Comment by lelopes05** [comment]
> This is the right file, but you have not updated to the latest version yet. Please download the [latest release](https://github.com/csutorasa/XOutput/releases/latest).

If you can do anything about this i would be really greatfull.

**Comment by lelopes05** [comment]
[XOutput.log](https://github.com/csutorasa/XOutput/files/3337566/XOutput.log)
here is my log file after replicating the settings change and behavior from OP

**Comment by csutorasa** [comment]
The lagging issue should be resolved after the devices are filtered correctly as they are in the latest development release. I have done some updates on the trigger detection. Please try to use [it](https://ci.appveyor.com/project/csutorasa/xoutput/build/artifacts).
