### ISSUE TITLE
left stick to D´pad is posible?

### ISSUE THREAD

**Issue by lawuealacago** [csutorasa/XOutput#59]
thanks for your great job
i need assign left stick on dpad, because i have a arcade stick and no detect a dpad but i have a left stick and the game need a dpad 

sorry my english is bad :)

**Comment by csutorasa** [comment]
Fixed in v3.13.

**Comment by lawuealacago** [comment]
tnx

**Comment by lawuealacago** [comment]
![20180902_144958](https://user-images.githubusercontent.com/42722626/44959220-61f27180-aec1-11e8-9c91-30af78ed0fc5.jpg)
not work :(
the pcb is a zero delay

**Comment by csutorasa** [comment]
I thought you have no DPad. If you have dpad, now it is not possible. I will fix this in 4.0, but there is not ETA yet on that version.

**Comment by csutorasa** [comment]
Fixed in v3.19.
