### ISSUE TITLE
Show true axis output (fix Inverted axis)

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#6]
The directional boxes are nice, great work, but shouldn't they show the actual output?
To have the correct directions i have to invert LY and RY which is normal, but the new boxes show as inverted output.
Checked in game and with [xinputest.exe](http://file.jayceooi.com/2009/01/xinputemu3.zip)

**Comment by csutorasa** [comment]
This might be an actual bug. I will investigate it soon.

**Comment by csutorasa** [comment]
Approved, can be reproduced. Fixed in version 1.7.1.
