### ISSUE TITLE
Controller randomly disconecting 

### ISSUE THREAD

**Issue by EarendilStrife** [csutorasa/XOutput#64]
Hi, trying to use a generic gamepad with Hollow Knight. Everything seems fine until controller stops working randomly for some seconds, then comes back, goes off again and again.

**Comment by csutorasa** [comment]
I have never seen an issue like that. If the controller is connected, and ready to use (correct drivers) then it should work continuously. Is it only happening with Hollow Knight? Is your CPU overloaded (95%+) while playing?
