### ISSUE TITLE
XOutput 3.14 vibration bug

### ISSUE THREAD

**Issue by LordVanHell** [csutorasa/XOutput#67]
Hello I Installed XOutput 3.14 With VIGem Bus Emulator, and the vibration dont work it, all devices are installed Correctly and my pc are fulll Update...

**Comment by csutorasa** [comment]
Is it working when you press the test button?

**Comment by LordVanHell** [comment]
> 
> 
> Is it working when you press the test button?

yes he works when the test button is pressed but when using it in video games the vibration does not work as in 3.13
