### ISSUE TITLE
Unassigned input by default

### ISSUE THREAD

**Issue by alfrix** [csutorasa/XOutput#7]
Currently the buttons come preassigned with button 1, since all of the dinput gamepads that i have don't have a '13' button to assign to the home button i have been doing a workaround using axis 5 which isn't used in any of them, please make the default config unassigned/nil

**Comment by csutorasa** [comment]
I think this use-case is covered by the [README.md](https://github.com/csutorasa/XOutput/blob/master/README.md) file. If you do not want to use any input, but a static value instead, you can set the minimum and maximum values manually.
For example if you do not want to use the DPad at all, set both minimum and maximum values to 0.

Unassigned would not work properly with axes though. The program cannot know if you want it to be centered or positioned to a fix value. I think, that you need to give a static value, is more useful in the long run.

Tell me if your issue can be resolved with this method.

**Comment by alfrix** [comment]
Think the case where the gamepad doesn't have all the necessary buttons/axes
you are recommending a workaround, setting the button to 'Axis 1' 0 0 works, but a special state of unassigned/disabled is a more elegant solution

**Comment by csutorasa** [comment]
Static value option will be added to the dropdown menu. If it is selected, instead of minimum and maximum, a single value can be set.

**Comment by alfrix** [comment]
![captura](https://user-images.githubusercontent.com/1247237/36073454-9a885110-0f0f-11e8-9374-a0aad71d6992.PNG)

**Comment by csutorasa** [comment]
Added to v1.8
