### ISSUE TITLE
Missing Trigger Detection

### ISSUE THREAD

**Issue by arthurthlee** [csutorasa/XOutput#72]
Hello,
I have finally gotten the chance to investigate why the triggers on my NYKO Playpad Pro are not detected in XOutput.

Upon tracing, I put a breakpoint at line 422 in DirectDevice.cs, and I added a line: 
var test = joystick.GetObjects();
In order to see if it was just that my triggers were being filtered out. It turns out that SharpDX's list of Joystick objects doesn't even include the triggers on my controller; GetObjects returns back 24 objects, none of which map to my triggers (I think). I can see that the project is using SharpDX 4.2.0.0. I am currently investigating if a newer version of SharpDX would be able to detect the triggers, and what library this website uses which DOES manage to detect them:
http://html5gamepad.com/

If you have any knowledge on SharpDX's joystick class and its list of inputs, please advise.

Thanks,
ruhtraeel

**Comment by csutorasa** [comment]
SharpDX uses the Directinput API of DirectX. The API defines enums that are processed, so you should check the `DeviceObjectTypeFlags` [enum values](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb321120(v%3Dvs.85)) on the type of objects (returned from `GetObjects()`). As far as I know the trigger should be an object with some special type values. Maybe you can recheck all of the types on all objects if you can find it. Please be aware that some axes have multiple uses (e.g. value axis and force feedback).

If you can find the real ObjectType then I can modify the trigger detection. If you are sure that SharpDX cannot find the proper objects, maybe you should report a bug at [SharpDX](https://github.com/sharpdx/SharpDX).

**Comment by ruhtraeel** [comment]
Hello,
I can't seem to find the objects that map to the triggers on my DirectInput controller. The objects that are returned by SharpDX have DeviceObjectTypeFlags of either a pushButton (16 of them), an absoluteaxis (of which there are 6; none of which seem to map to the triggers on my controller), a hat switch (not sure what this is) and a collection (also not sure what this is). None of these seem to map to the triggers, so I'm pretty sure that it's SharpDX that isn't finding the proper objects. I will submit a bug over there.

**Comment by csutorasa** [comment]
Hat switch is the DPad, and Collections are just groups for objects (usually x-y axis pairs). None of those should be triggers.

**Comment by csutorasa** [comment]
SharpDX seems to be archived 29 Mar 2019. I am not sure that this issue can be handled with SharpDX.
