### ISSUE TITLE
g920 wheel accelerator not recognized by xoutput

### ISSUE THREAD

**Issue by whattheflukz** [csutorasa/XOutput#73]
the accelerator pedal isn't recognized and will not map to a button on the controller. both images below i'm pushing the throttle to about halfway. A1 on the axes in xoutput is the steering wheel
<img width="299" alt="capture" src="https://user-images.githubusercontent.com/22034966/51277070-8c425880-19a4-11e9-8099-9727cd1a545f.PNG">
<img width="860" alt="1c" src="https://user-images.githubusercontent.com/22034966/51277108-a8de9080-19a4-11e9-83e7-fae81f352029.PNG">

edit
it appears that the input is recognized just recording of it is not 
<img width="571" alt="capture1" src="https://user-images.githubusercontent.com/22034966/51278933-f27daa00-19a9-11e9-938e-d1da144622c1.PNG">

**Comment by csutorasa** [comment]
This is recognized as a Slider and should have the same root cause with #83.

**Comment by csutorasa** [comment]
Can you check if it works in v3.18?
