### ISSUE TITLE
Start the app silent without taskbar icon

### ISSUE THREAD

**Issue by 2k9** [csutorasa/XOutput#74]
Hi, is there a way to start the application (with or without AHK) in a silent mode?
I'm fine with a tray icon, but the taskbar window (even if minimized) always kicks me out of my games when I start the application via a hotkey command.

Appreciate an answer!

**Comment by csutorasa** [comment]
Hi, I see your problem, I will look into it.

**Comment by csutorasa** [comment]
Check the 3.15 version, it should not open the window in `--minimized`.
