### ISSUE TITLE
Multiple force feedback issues for MAYFLASH GCN Adapter

### ISSUE THREAD

**Issue by ArleCamille** [csutorasa/XOutput#75]
I have seen numerous issues for force feedback not working, but since this seems to be a unique case which only applies to this kind of controller, I am leaving a separate issue here.

![mayflash_diag](https://user-images.githubusercontent.com/33932097/52830293-8fe80d00-3113-11e9-8511-08e57e6e54ab.PNG)

Above is what is shows for the diagnostic window. It shows that there are two force feedback motors, satisfying the requirement. However, there are very peculiar issues when I actually try to activate force feedback.

First, when I start force feedback test, its intensity is NOT uniform. Each time I run the test, it goes from a very subtle vibration I can hardly feel from an average XONE controller rumble, but in average, it is significantly weaker than what I can expect from a GCN controller. However, when I actually play the game, the controller doesn't vibrate at all. The game in question is Monster Hunter: World. However, it uses Steam API to translate XInput into Steam Controller input, barring the case of the game compatibility issue.

For reference, a Gamecube controller has a large single force feedback motor which Mayflash adapter seperates as two motor axes.

![mayflash_rumble_reference](https://user-images.githubusercontent.com/33932097/52830587-b8243b80-3114-11e9-85b6-6967585a7bf2.PNG)

**Comment by csutorasa** [comment]
I have added a possible force feedback intensity fix. Can you try v3.22?

**Comment by ArleCamille** [comment]
Got the force feedback working in the latest version (both in the input end and the output end; the latter tested using a Windows Store app called "Game Controller Tester"); still not working in Monster Hunter: World. However, I think the issue is now tied with Steam, not the issue of XOutput. Thank you for the response.
