### ISSUE TITLE
Guide for install XOutput and hide real device

### ISSUE THREAD

**Issue by LLltirlec** [csutorasa/XOutput#79]
@csutorasa in this video full guide for install XOutput and hide device device
[Youtube]( https://youtu.be/QfYxjMWLVYw)
[Edited and compiled file](https://drive.google.com/open?id=1Zn3ew9JGWFcbQPWNJbgm-gXOvKfmm0Kc)
[HidGuardian v1 driver installation](https://docs.vigem.org/#!hidguardian-v1-installation.md)
#68 #28

**Comment by csutorasa** [comment]
I will install HidGuardian and test this change. If it works I am happy to include it.

Thank you for the video tutorial of the installation steps.

**Comment by csutorasa** [comment]
Added to v3.16

**Comment by VFansss** [comment]
Sorry for re-opening this issue, but I have to write a guide on how to use XOutput with [my game fix](https://github.com/VFansss/mgs2-v-s-fix/Wiki), and I want to be sure that I've understand everything right.

With latest version, to correctly "hide" a gamepad, you have to mandatory install [Hidguardian v1 driver](https://forums.vigem.org/topic/271/hidguardian-v1-driver-installation) manually ?

Why it has been discontinued? Its planned to be included inside ViGEm, or what?

I take this opportunity to say that XOutput is a masterpiece. Thanks ❤️

**Comment by emanuelntb** [comment]
Does this method still works? 
I tried as the video/documentation describes, but after 
.\Devcon.exe install HidGuardian.inf Root\HidGuardian
I got devcon.exe failed.
