### ISSUE TITLE
Left Analog Stick isnt recognized in configuration

### ISSUE THREAD

**Issue by dethgiD** [csutorasa/XOutput#81]
So in the log of XOutput I see that it recognizes the X and Y axis, but when I go to configure it, for some reason it just doesn't show it. I tried to map the axis in the settings file but a weird thing happens: Left Stick only moves when I have LT or RT pressed at the same time. It worked fine before I reset my windows.
[XOutput.log](https://github.com/csutorasa/XOutput/files/3168816/XOutput.log)

**Comment by csutorasa** [comment]
Can you tell me which version you used before Windows reset?

**Comment by csutorasa** [comment]
Please make sure that DirectX and all the drivers are up to date. Reopen if needed.
