### ISSUE TITLE
[TWIN USB JOYSTICK] VIBRATION  DOES NOT WORK ON VERSION 3.15 3.16

### ISSUE THREAD

**Issue by pablo2030** [csutorasa/XOutput#82]
Hello friends I just tested the new version xoutput with the hidguardian everything works well except for the vibration for my **TWIN USB JOYSTICK it works only on the version 3.11 everything works well everything in this version**
![Xoutput 3 16 3 15 jpeg](https://user-images.githubusercontent.com/33200597/57657765-443ee580-75d4-11e9-905b-4926bb5f243e.png)

**Comment by csutorasa** [comment]
Hi, in version 3.11 ViGem client was updated in the application. I am not sure how to update to the newer version of ViGem, but I will ask @nefarius.

**Comment by pablo2030** [comment]
I think I'll stay on version 3.11 but please fix the vibration problem on the 3.16 I'd like to upgrade to this version with the hidguardian mode good luck friend

**Comment by csutorasa** [comment]
Could you copy the output of the following script run in PowerShell as administrator?
```powershell
Get-ViGEmBusDevice
```

**Comment by pablo2030** [comment]
Hello I think there is a misunderstanding when I say 3.11 I'm talking about xoutput 3.11 no ViGem 3.11 the vibration does not work on version 3.15 3.16 of xoutput except for version 3.11 of xoutput

**Comment by csutorasa** [comment]
Try v3.17

**Comment by pablo2030** [comment]
Everything works well the Hip Guardian + the vibration dude you're my little jesus I'll thank you if there is any problem I'll sign you
