### ISSUE TITLE
DualShock 3 doesn't detect LY axis

### ISSUE THREAD

**Issue by VidarPT** [csutorasa/XOutput#83]
![Xoutput DS3](https://user-images.githubusercontent.com/7354861/57938247-b73fa900-78bf-11e9-94db-66666065c14d.png)

Everything else is working fine but Xoutput doesn't detect the LY axis for configuration. 
Note that I had to instal PSNow because nothing was working prior to that - the program detected the controller but none of the inputs worked. Installing PSNow also installs Sony's official DInput drivers so the system now detects it correctly. I can get the controller working under Steam's emulation and it also works under the old ScpServer even without the PSNow drivers.

[XOutput.log](https://github.com/csutorasa/XOutput/files/3192095/XOutput.log)

![Y axis works](https://user-images.githubusercontent.com/7354861/57939055-587b2f00-78c1-11e9-8799-752b5b75175b.png)

Here's a screenshot showing the LY axis tilted. Just to show that the controller is working right.

I'd also like to note that pior to the installation of PSNow, Xoutput detected the controller as a game controller. After installing PSNow, I now need to click "Show all input devices" for the controller to show up.

**Comment by FatheredPuma81** [comment]
Considering this is 17 days old i'm pretty certain literally no one cares.
I have an O. Xbox S controller and the left stick entirely isn't recognized. The dumb part is I can manually add it into the config and it works fine... you know... when i'm pressing other buttons... so practically worthless...

**Comment by csutorasa** [comment]
Can you tell me which DirectInput axes show anything on the left side when you move your controller? For example:

- RX -> A1 changes
- RY -> A4 changes

**Comment by FatheredPuma81** [comment]
> Can you tell me which DirectInput axes show anything on the left side when you move your controller? For example:
> 
> * RX -> A1 changes
> * RY -> A4 changes

If you're replying to me it's none. The issue is that it literally doesn't recognize it. Video: https://youtu.be/JBZz9CPypy4 (should be up within 2-3 minutes of this post)

**Comment by csutorasa** [comment]
I will try to create a test version for this as well.

**Comment by VidarPT** [comment]
The LY is working now. thanks.  There's still some weird stuff going on though:

Firstly, the RY is now inverted by default. I had to click the invert option to make it straight.
Secondly, the X and O (A and B respectively) are detected as sliders. This makes it so that the emulated xbox controller thinks these buttons are constantly pressed as shown in the screenshot. It is true that in the PS3 controller these buttons (and the missing square and triangle buttons) are actual pressure sensitive. I don't think the xbox controller has this feature though so the program should, in my opinion, ignore this feature entirely and emulate them as regular buttons. 
Thirdly, I have no idea what those A7 and A8 axis are. I wonder if it's the gyro or  maybe it's the missing sliders for the square and triangle buttons.

![Sliders](https://user-images.githubusercontent.com/7354861/58837381-4801dd00-8653-11e9-936e-e2bc65f7b29a.png)

**Comment by csutorasa** [comment]
First of all can you send me the a new log file?

**Comment by VidarPT** [comment]
[XOutput.log](https://github.com/csutorasa/XOutput/files/3261215/XOutput.log)

**Comment by csutorasa** [comment]
I think the current developer release should be working good for sliders and axes as well. This is unfortunately not release ready yet, but you can try it.

**Comment by csutorasa** [comment]
And yes you can create separate issues for the bugs.

**Comment by VidarPT** [comment]
> I think the current developer release should be working good for sliders and axes as well

I tried it and the RX doesn't work now.

[XOutput.log](https://github.com/csutorasa/XOutput/files/3298214/XOutput.log)

Z Rotation = RY
Z Axis = RX

The rotation works, but the axis is stuck full green. LT is still inverted.
![RX LT](https://user-images.githubusercontent.com/7354861/59625209-9ec9e500-9130-11e9-9e7f-dac0e8e9d8b2.png)

**Comment by csutorasa** [comment]
A new developer version is available. If I am right, all the axes should work now, not sure about the sliders.

By default Y axis is inverted, if your controller does not invert LT, but says it is Y rotation, then I think my application is working properly. I think `Y Axis` is working fine for you, with one of my controllers `Y rotation` is working fine, because of the default inversion.

**Comment by csutorasa** [comment]
@VidarPT can you confirm that RX is working with the latest developer version?

**Comment by VidarPT** [comment]
> 
> 
> @VidarPT can you confirm that RX is working with the latest developer version?

Yup, it's working. RY is inverted though, not sure if that's working as intended.

[XOutput.log](https://github.com/csutorasa/XOutput/files/3364297/XOutput.log)
