### ISSUE TITLE
I might as well add my own Left Trigger issue

### ISSUE THREAD

**Issue by FatheredPuma81** [csutorasa/XOutput#86]
Controller: Original Xbox S controller.
Issue: Left trigger isn't recognized.
Fix: Manually added the left stick in the config file.
Result: I can only use the left stick while using the right stick or triggers.
Result of fix: Not Fixed.

Looking at the age of the rest of them it's doubtful this will be fixed for quite a long long while. Sadly I was even using a very old version of xoutput that recognized it fine until it suddenly stopped being able to emulate the controller...

Edit: After doing a little downloading I found out that version 3.12 is where it breaks.

**Comment by csutorasa** [comment]
I think I know where it broke. It should be 0cb5799 where I tried to separate the slider and axis functionality. I cannot promise any ETA but will post here if I have a test version for you.

**Comment by csutorasa** [comment]
Can you test the [latest development release](https://ci.appveyor.com/project/csutorasa/xoutput/build/artifacts)?

**Comment by FatheredPuma81** [comment]
> Can you test the [latest development release](https://ci.appveyor.com/project/csutorasa/xoutput/build/artifacts)?

Just tested it and it's fixed :D.

**Comment by csutorasa** [comment]
Can you check the #83 issue as well, as it changes the axis detection as well?

**Comment by FatheredPuma81** [comment]
> Can you check the #83 issue as well, as it changes the axis detection as well?

I don't have a Dualshock 3 controller sadly to test if it fixed that guys issue.

**Comment by csutorasa** [comment]
Released in v3.18
