### ISSUE TITLE
Will everything works fine if I install only Vigem?

### ISSUE THREAD

**Issue by DuckerMan** [csutorasa/XOutput#88]

**Comment by csutorasa** [comment]
Yes, it should be fine.

**Comment by DuckerMan** [comment]
But I've a problem. Contoller works fine and games see it on my Windows 7 PC.

But games don't see my controllet on my Windows 10 Laptop.

I tried same game: The Walking Dead Season 1 and 2

**Comment by csutorasa** [comment]
Start the application on Windows 10, then start the emulated controller. If it does not work, just exit the application and there is an `XOutput.log` file next to the application. Please attach it.

**Comment by DuckerMan** [comment]
It seems that my controller's settings were reset. Now everything's fine, Thanks
