### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by rottenhands** [csutorasa/XOutput#90]
When i launch the program it closes immediatly 
Here's the log

> 2019-06-25 03:24:10.884 -03:00 INFO  XOutput.UI.Windows.MainWindow..ctor: Starting XOutput in normal window
2019-06-25 03:24:11.196 -03:00 INFO  XOutput.Tools.LanguageManager.set_Language: Language is set to English
2019-06-25 03:24:11.202 -03:00 INFO  XOutput.UI.Windows.MainWindowViewModel.Initialize: Loading settings was successful.
2019-06-25 03:24:11.247 -03:00 ERROR XOutput.UI.Windows.MainWindowViewModel.UnhandledException: System.DllNotFoundException: No se puede cargar el archivo DLL 'vigemclient.dll': No se puede encontrar el módulo especificado. (Excepción de HRESULT: 0x8007007E)
   en Nefarius.ViGEm.Client.ViGEmClient.vigem_alloc()
   en Nefarius.ViGEm.Client.ViGEmClient..ctor()
   en XOutput.Devices.XInput.Vigem.VigemDevice.IsAvailable()
   en XOutput.UI.Windows.MainWindowViewModel.Initialize(Action`1 log)
   en XOutput.UI.Windows.MainWindow.<WindowLoaded>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

(the error line says "Unable to load DLL 'vigemclient.dll': The specified module could not be found" sorry for it being in spanish)

**Comment by csutorasa** [comment]
Do you have ViGEm installed?

**Comment by rottenhands** [comment]
Yes, I installed before downloading Xoutput

**Comment by Laximas** [comment]
I have the same issue, I also tried the development release of XOuput which doesnt instantly crash, it first shows that ViGEm is not installed even though it is like in the image below and then it crashes. Not sure if this is a ViGEm side problem.

![image](https://user-images.githubusercontent.com/39433195/60550551-10a94d80-9d31-11e9-9ba8-bdae43c15515.png)

**Comment by Laximas** [comment]
After some digging I found a post that suggested you updated DirectX and installed both the 32 and 64 bit versions of 2015 visual c redistributable. In my case I knew DirectX was updated but when I checked which redistributables I had installed I noticed that only the 64 bit was installed on my system. After installing the 32 bit one the problem was solved! I hope @rottenhands can confirm. If this is the case, you can add it in the requirements of the program.

**Comment by csutorasa** [comment]
I think proper DirectX install is required for both input and output of the data. Thank you for the investigation, I will update the README.md.

**Comment by rottenhands** [comment]
Okay, I installed the 32 bit redistributables and it worked, so yeah, thanks @Laximas for suggesting it.

**Comment by Laximas** [comment]
Sorry to BUMP, but I just noticed the readme update and I believe it's not clear what needs to be installed. DirectX doesn't have a 32-bit and a 64-bit version. The actual requirements are:
-DirectX
-Visual C++ Redistributable for Visual Studio 2015 32-bit
-Visual C++ Redistributable for Visual Studio 2015 64-bit

Sorry again, just trying to help.

**Comment by csutorasa** [comment]
Thank you for the information, I will update it.
