### ISSUE TITLE
Button 3 and button 6 not detected

### ISSUE THREAD

**Issue by mlody95pl** [csutorasa/XOutput#94]
In latest version (3.19) I can't bind button 3. Previous version was fine. I have similar issue in CEMU.
My log: https://pastebin.com/r64Ht2Jb

**Comment by csutorasa** [comment]
Is it only Button 3 or is there any more buttons that does not work?

**Comment by mlody95pl** [comment]
Button 6 also doesn't work. No, it's simple bluetooth gamepad with binary buttons and triggers, two analogs and 1 POV.

**Comment by csutorasa** [comment]
Can you please send me log from current and previous versions?

**Comment by csutorasa** [comment]
And I can see from the log that neither SCPToolkit nor ViGEm is working correctly on your computer. Make sure that you have everything installed including:

- DirectX
- Visual C++ Redistributable for Visual Studio 2015 32-bit
- Visual C++ Redistributable for Visual Studio 2015 64-bit
- all the drivers for your controllers
- .Net Framework 4.5.2 if you do not have Windows 10
- the official XBox 360 controller drivers.

**Comment by mlody95pl** [comment]
[XOutput_last_working_3.18.log](https://github.com/csutorasa/XOutput/files/3407807/XOutput_last_working_3.18.log)
[XOutput_not_working_3.19.1.log](https://github.com/csutorasa/XOutput/files/3407811/XOutput_not_working_3.19.1.log)

I'm 100% sure that everything is correctly installed on my laptop. Latest versions (3.19.X) don't detect my gamepad correctly. 
![image](https://user-images.githubusercontent.com/4082647/61480846-2a849a80-a997-11e9-82e4-7d073caffcb4.png)
As you can see some buttons is not detected

**Comment by mlody95pl** [comment]
Any chance to fix that bug ?

**Comment by csutorasa** [comment]
We will see, I will try for sure.

**Comment by csutorasa** [comment]
You can try 3.20 now, and if it still does not work then please send me a new log file, as I added more info.

**Comment by mlody95pl** [comment]
[XOutput.log](https://github.com/csutorasa/XOutput/files/3425331/XOutput.log)
Still doesn't work. I have similar bug in CEMU, so maybe you use same library in your app ?

**Comment by mlody95pl** [comment]
[settings.txt](https://github.com/csutorasa/XOutput/files/3425340/settings.txt)

**Comment by csutorasa** [comment]
Can you confirm that you these are all working? Do you miss the button 13 as well?
- 6 axes
  - X
  - Y
  - Z
  - Z rotation
  - Accelerator
  - Brake
- 12 buttons
  - 1
  - 2
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 14
  - 15

**Comment by mlody95pl** [comment]
My gamepad doesn't have 14 and 15, and 13 too

**Comment by csutorasa** [comment]
Okay then I think I know where the problem is. I will revert the latest change, and fix this for you today.

**Comment by csutorasa** [comment]
Please try it in version 3.22.

**Comment by mlody95pl** [comment]
It's working now ! Thanks. Can you tell me where issue was ?

**Comment by csutorasa** [comment]
The name and the number of the buttons are calculated from the of the [ObjectId](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb152001(v=vs.85)). They are usually in a continuous increasing order (like button 1, button 2, ...). In your case there are some missing ones (3, 6, 13).

SharpDX gives you an array of the button values (0-11), and I was indexing it with numbers (0,1,3,4,6,7,8,9,10,11,13,14). So the issue was, that I was indexing the array with the ObjectIds and not their actual position.

I hope it can be understood. but the change can be found here as well d4af27d.

**Comment by UxmanX** [comment]
Thanks a lot. I got your version from SourceForge and exact issue was encountered. Glad to see you fixed it.

**Comment by xMarvicS** [comment]
hey I have the same issue with my right and left triggers (my triggers are working perfect without xoutput) can you fix mine too?
![resim_2021-04-13_110921](https://user-images.githubusercontent.com/82439891/114519068-b26d0680-9c48-11eb-853c-c94e424d4641.png)

**Comment by UxmanX** [comment]
Which version are you using right now?

Been a while, I don't even have that controller to test now.

**Comment by xMarvicS** [comment]
I think our controllers are not same. Mine is steelseries nimbus+. Im using v3.32 I think.
