### ISSUE TITLE
Greek layout issue

### ISSUE THREAD

**Issue by Laximas** [csutorasa/XOutput#95]
The buttons in this screen in Greek hide some words, can you dynamically push the button to the right or do you want me to rephrase this translation to make it smaller?
![image](https://user-images.githubusercontent.com/39433195/60766940-17c9b600-a0b9-11e9-89dc-94d68acbf059.png)

Also, I see english here but I have translated this. Have I done something wrong or is it something else?
![image](https://user-images.githubusercontent.com/39433195/60767076-f36ed900-a0ba-11e9-89c0-89f5b70a8baf.png)

Version here can be translated but it's not available in json.
![image](https://user-images.githubusercontent.com/39433195/60767085-0bdef380-a0bb-11e9-8f36-8578823066a8.png)

Finally, in configuration I can see SelectedValue and SelectedDevice but they are also not available in json to be translated.
![image](https://user-images.githubusercontent.com/39433195/60767100-3b8dfb80-a0bb-11e9-8206-34804c7e197a.png)

**Comment by csutorasa** [comment]
- Settings layout is is a valid bug, I will fix it
- When you first start XOutput it will log in English, but if you set it to Greek, save configuration, and restart, then it should be all Greek then. I will look into that, but please try after a restart.
- Version is missing, I will fix it
- SelectedValue and Selected device is a valid bug, I will fix it

**Comment by Laximas** [comment]
Yeah, you're right about the 2nd one but there's a new problem. If I choose any language and select save, it doesn't save my choice in the txt file. I also tried changing the language manually in the txt and then attempted to start the software but it did not read the correct language.

**Comment by csutorasa** [comment]
I will add this to 3.19.1 hotfix.
