### ISSUE TITLE
problem 4 player Game(coop) please fix problem

### ISSUE THREAD

**Issue by fapam4** [csutorasa/XOutput#96]
hi

Please Problem my game 
When playing I recognize two gamepad
Each gamepad identifies two gamepad

Give it an update to disable it
Add an option to disable the extra gamepad.
Me can not play such multiplayer games

When playing as if played by two gamepad just one gamepad, you have difficulty choosing the character of the game

I'm having trouble choosing a character(coop Games)4 player game
It's as if two copying gamepad

**Comment by fapam4** [comment]
https://ibb.co/RPXXztg. Pic Problem

Must Just Controller(XBOX 360 For Windows)
Usb Joystick Additional.Problem Program

**Comment by csutorasa** [comment]
I am not sure what the problem is, but:

- if you would like to disable the original input you must install HidGuardian, run the XOutput as admin and setup the HidGuardian for the input device
- if you would like to have more XBox controllers, then you need to `Add controller`, press `Start` on all of them

**Comment by fapam4** [comment]
I did the steps Not Fix Problem.Gamepad Orginal Can not Disable
The main problem is that One Gamepad.Gets Two Gamepad
If changes are made on a Gamepad,Not additional Gamepad.
What can I do to solve the problem?

You New Update Fix ?Or Not?
For 4 Player Game(Coop Game)

**Comment by fapam4** [comment]
I did the steps Not Fix Problem.Gamepad Orginal Can not Disable
The main problem is that One Gamepad.Gets Two Gamepad
If changes are made on a Gamepad,Not additional Gamepad.
What can I do to solve the problem?

You New Update Fix ?Or Not?
For 4 Player Game(Coop Game)

**Comment by fapam4** [comment]
https://igg-games.com/stick-fight-game-free-707311334-download.html

Test this game.I understand what I mean

**Comment by csutorasa** [comment]
I understand that you want to remove original input, and use only XOutput. HidGuardian is working, try to follow #79 and `README.md` file.

**Comment by fapam4** [comment]
Very Very Thanks For Help
The problem was solved
