### ISSUE TITLE
Fecha sozinho_Resolvido

### ISSUE THREAD

**Issue by manstenun** [csutorasa/XOutput#98]
Já fiz tudo, instalei todos os programas necessários, mas na hora que abro ele fecha em seguida

**Comment by csutorasa** [comment]
Please attach `XOutput.log` file.

**Comment by manstenun** [comment]
[XOutput.log](https://github.com/csutorasa/XOutput/files/3381869/XOutput.log)

**Comment by manstenun** [comment]
Espero que resolva.
