### ISSUE TITLE
problem with last version

### ISSUE THREAD

**Issue by evergarden321** [csutorasa/XOutput#99]
I dowloaded now the last version and i have problems with the program recognising  L2 and R2 of my controller as rotation x and y appart for button  B8 and B9 like the other version i have . What could be the problem?

PD: i actualized because i want the game to stop recognize the controller as 2 (the p4 wired controller and the xoutput one) can i do that with this version?

**Comment by csutorasa** [comment]
Can you send me the `XOutput.log` file?

**Comment by evergarden321** [comment]
[XOutput.log](https://github.com/csutorasa/XOutput/files/3377659/XOutput.log)
[34281ae4-b5ff-460b-a2a0-d3455031312bXOutput.log](https://github.com/csutorasa/XOutput/files/3377660/34281ae4-b5ff-460b-a2a0-d3455031312bXOutput.log)
here are the 2 docs , log and the other one

**Comment by evergarden321** [comment]
[XOutput.log](https://github.com/csutorasa/XOutput/files/3377680/XOutput.log)
this is the log of the version where everything works fine in case u need it

**Comment by csutorasa** [comment]
I was unable to find the error, please try to check all versions between 3.15 and current (3.19.1) if it works. So I can find where the application went wrong.
